Repository Mo-yoy/Moyo-Frontend, pull requests merged in 2025-02, with the labels that each got.

#21 Fix : UserProfileAvatar 스펙 수정 (fallback 이미지 추가 및 gray color 변경)
  src/App.tsx
  src/assets/images/img_default_user_profile.png
  src/assets/images/index.ts
  src/common/components/UserProfileAvatar.tsx
Labels: size/S, 🎨 Design, 🔨 Refactor, 🐹 연또

#19 Feat: 공통 Header를 구현합니다.
  src/Menu/page.tsx
  src/common/components/Header.tsx
  src/common/constants/zIndex.ts
Labels: size/M, ✨ Feature, 🐻 쩡우

#26 Feat : 공통 Spacer 컴포넌트 구현
  src/Menu/page.tsx
  src/common/components/Spacer.tsx
Labels: size/M, ✨ Feature, 🐹 연또
