Repository Mo-yoy/Moyo-Frontend, pull requests merged in 2025-01, with the labels that each got.

#6 Chore: lang 속성을 ko로 변경합니다.
  index.html
Labels: 📦 chore

#4 Chore: @emotion/styled 의존성을 추가합니다.
  package.json
  pnpm-lock.yaml
Labels: 📦 chore

#14 Feat: user list item box 공통 컴포넌트 구현
  src/Menu/page.tsx
  src/common/components/UserListItemCard.tsx
  src/common/types/utilt.ts
Labels: feat, size/M

#12 Feat: Pretendard font를 적용합니다.
  index.html
  public/fonts/PretendardVariable.woff2
  src/Menu/page.tsx
  src/common/styles/GlobalStyles.tsx
Labels: feat, size/S

#15 Feat: user profile Avatar 공통 컴포넌트 구현
  src/Menu/page.tsx
  src/common/components/UserProfileAvatar.tsx
Labels: size/M, ✨ Feature, 🐹 연또
